apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twenty-nfs
  namespace: kooplex-veo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 19Ti
  storageClassName: default-cinder
